/**
 * Cryptographic & Verification Utilities for UTVN
 * - UTID generation
 * - 64-char IRN hash generation (Govt IRP compliant: SHA256 of SellerGSTIN + FY + DocType + DocNum)
 * - Tamper-evident Audit Block Chaining
 * - E-Invoice QR Code payload serialization
 */

export function generateUTID(region: string = 'IND'): string {
  const year = new Date().getFullYear();
  const randomPart = Math.floor(100000 + Math.random() * 900000);
  const checksum = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `UTVN-${year}-${region}-${randomPart}-${checksum}`;
}

/**
 * Generate a standard 64-character Indian E-Invoice IRN (Invoice Reference Number)
 * In production, this is the SHA-256 hash generated by the Invoice Registration Portal (IRP/NIC).
 */
export function generateIRN(sellerGstin: string, docNum: string, fy: string = '2025-26'): string {
  const rawString = `${sellerGstin}${fy}INV${docNum}`.toUpperCase();
  // Deterministic 64-char pseudo-hash for demonstration
  let hash = '';
  for (let i = 0; i < 64; i++) {
    const charCode = (rawString.charCodeAt(i % rawString.length) * (i + 13) * 31) % 16;
    hash += charCode.toString(16);
  }
  return hash.toLowerCase();
}

/**
 * Tamper-evident cryptographic block hash
 */
export function computeBlockHash(prevHash: string, dataPayload: string, timestamp: string): string {
  const combined = `${prevHash}|${timestamp}|${dataPayload}`;
  let hash = '';
  for (let i = 0; i < 32; i++) {
    const val = (combined.charCodeAt(i % combined.length) * 37 + i * 17) % 256;
    hash += val.toString(16).padStart(2, '0');
  }
  return hash;
}

/**
 * Generate standard Indian B2B e-invoice QR code content
 */
export function generateEInvoiceQRData(
  sellerGstin: string,
  buyerGstin: string,
  docNo: string,
  docDate: string,
  totalValue: number,
  itemCount: number,
  irn: string
): string {
  return JSON.stringify({
    SellerGSTIN: sellerGstin,
    BuyerGSTIN: buyerGstin,
    DocNo: docNo,
    DocTyp: 'INV',
    DocDt: docDate,
    TotInvVal: totalValue,
    ItemCnt: itemCount,
    MainHsnCode: '84713010',
    Irn: irn,
    IrnDt: new Date().toISOString().split('T')[0]
  });
}

/**
 * Generate Peppol BIS 3.0 / UBL XML sample
 */
export function generateUblXml(utid: string, poId: string, invoiceId: string, sellerName: string, buyerName: string, amount: number, currency: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
  <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0</cbc:CustomizationID>
  <cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
  <cbc:ID>${invoiceId}</cbc:ID>
  <cbc:IssueDate>${new Date().toISOString().split('T')[0]}</cbc:IssueDate>
  <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
  <cbc:DocumentCurrencyCode>${currency}</cbc:DocumentCurrencyCode>
  <cac:OrderReference>
    <cbc:ID>${poId}</cbc:ID>
  </cac:OrderReference>
  <cac:AdditionalDocumentReference>
    <cbc:ID>${utid}</cbc:ID>
    <cbc:DocumentTypeCode>UTVN-PROTOCOL-V1</cbc:DocumentTypeCode>
  </cac:AdditionalDocumentReference>
  <cac:AccountingSupplierParty>
    <cac:Party>
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>${sellerName}</cbc:RegistrationName>
      </cac:PartyLegalEntity>
    </cac:Party>
  </cac:AccountingSupplierParty>
  <cac:AccountingCustomerParty>
    <cac:Party>
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>${buyerName}</cbc:RegistrationName>
      </cac:PartyLegalEntity>
    </cac:Party>
  </cac:AccountingCustomerParty>
  <cac:LegalMonetaryTotal>
    <cbc:PayableAmount currencyID="${currency}">${amount.toFixed(2)}</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
</Invoice>`;
}
